language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - 10
  - 9
  - 8

install:
  - yarn

before_script:
  - yarn ci

script:
  - yarn build

after_success:
  - if [[ $TRAVIS_NODE_VERSION == "8" ]]; then yarn codecov; fi

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  provider: npm
  skip_cleanup: true
  email: uma.karimov@gmail.com
  api_key:
    secure: twwsNFb3twVqJWz1Wl+mRvsHuPVdBCrkNH4pB3JYjt9o3StfdXY1WXrNS5hOM+sGd8HFk6VartCMIbB7Cz38oECZ7E+9hJNXzQiLuYYP27R54jPzvca3U72urV4fvnexOGQaHL/KkExadcz3u0Wt+E4LU8kaSUTxKfqQdagjtEkHMKBQpea4Q8jsN8Y8vDZJsPTD9zucu/oAj09G4KDS4XFNNklnO7uwc/SeVCggS0YTjN0lcijcucPQxkS+5LFEqoO32cZLyIaQWix5lXTr5MMsL7YyI6Wyq5/c+LODRYxMVfX3QGPpF7OnDMPNFSNJxKgMXNQYBcoDSxm8W06mgyQ7a09vzVGnbkB1tYIq0vx066t/SxogyllAm3sUj6DOkLtIfzVE+JDoMMXDq9fNmEmno4X4y8xhP9bgj5WCNrdc2hAszhLq6gnN03xi6eL42nUZnnplT/yF+RG/1QuyB8hgwRtTrH2EsmNQF1dWQ9O1XUoHAc1k8YlFEoX2mIZ4+fQbs518pH9ZpPZ8dr6li/jLTE+rBrMpVpe/djhSt9TG9rXotS+O2bT0YYfor5MM1WYGbxXlUP3A81ZDmx+0CPUkbPEGZkIJTsUqhnaSNOr2gKv1SQWzONknOBUpikIjhhoeRKwWftIFWexyRxQgHZqrroI8zfWoVOosFllvPTw=
  on:
    tags: false
    branch: master
    repo: dcodeteam/http-client
    condition: "$TRAVIS_NODE_VERSION = 8"
