language: node_js

cache: yarn

notifications:
  email: false

node_js:
  - "8"
  - "10"

install:
  - yarn

before_script:
  - yarn ci

script:
  - yarn build

branches:
  except:
    - "/^v\\d+\\.\\d+\\.\\d+$/"

deploy:
  - provider: script
    skip_cleanup: true
    script: yarn codecov
    on:
      tags: false
      node_js: "8"
      branch: master
      repo: dcodeteam/react-google-maps

  - provider: npm
    skip_cleanup: true
    email: uma.karimov@gmail.com
    api_key:
      secure: $NPM_TOKEN
    on:
      tags: true
      node_js: "8"
      branch: master
      repo: dcodeteam/http-client
